<?php

namespace App\Enums;

enum Departamentos: string
{
    case SISTEMAS = 'SISTEMAS';
    case CONTABILIDAD = 'CONTABILIDAD';
    case AUDITORIA = 'AUDITORIA';
    case ADMINISTRACION = 'ADMINISTRACION';
    case RECURSOS_HUMANOS = 'RECURSOS HUMANOS';
    case UNIDAD_DE_PREINVERSION = "UNIDAD_DE_PREINVERSION";
    case SUENO_BICENTENARIO = 'SUENO BICENTENEARIO';
    case DESPACHO = "DESPACHO MINISTERIAL";
    case CORRESPONDENCIA = "CORRESPONDENCIA";
    case COMUNICACION = "COMUNICACION";
    case TRANSPARENCIA = "TRANSPARENCIA";
    case PLANIFICACION = "PLANIFICACION";
    case JURIDICA = "JURIDICA";
    case ASUNTOS_JURIDICOS = "ASUNTOS JURIDICOS";
    case ASUNTOS_ADMINISTRATIVOS = "ASUNTOS ADMINISTRATIVOS";
    case FINANCIERA = "FINANCIERA";
    case PRESUPUESTOS = "PRESUPUESTOS";
    case TESORERIA = "TESORERIA";
    case ACTIVOS_FIJOS = "ACTIVOS FIJOS";
    case SERVICIOS_GENERALES = "SERVICIOS GENERALES";
    case ADQUISICIONES = "ADQUISICIONES";
    case DIRECCION_GENERAL_DEL_SISTEMA_DE_PLANIFICACION_INTEGRAL_ESTATAL = "DIRECCION GENERAL DEL SISTEMA DE PLANIFICACION INTEGRAL ESTATAL";
    case DIRECCION_GENERAL_DE_SEGUIMIENTO_Y_COORDINACION = "DIRECCION GENERAL DE SEGUIMIENTO Y COORDINACION";
    case VICEMINISTERIO_DE_PLANIFICACION_Y_COORDINACION = "VICEMINISTERIO DE PLANIFICACION Y COORDINACION";
    case DIRECCION_GENERAL_DE_PLANIFICACION_TERRITORIAL = "DIRECCION GENERAL DE PLANIFICACION TERRITORIAL";
    case VICEMINISTERIO_DE_PLANIFICACION_ESTRATEGICA_DEL_ESTADO = "VICEMINISTERIO DE PLANIFICACION ESTRATEGICA DEL ESTADO";
    case DIRECCION_GENERAL_DE_EMPRESAS_ESTATALES = "DIRECCION GENERAL DE EMPRESAS ESTATALES";
    case DIRECCION_GENERAL_DE_PROMOCIÓN_DE_INVERSIONES = "DIRECCION GENERAL DE PROMOCIÓN DE INVERSIONES";
    case VICEMINISTERIO_DE_INVERSION_PUBLICA_Y_FINANCIAMIENTO_EXTERNO = "VICEMINISTERIO DE INVERSION PUBLICA Y FINANCIAMIENTO EXTERNO";
    case DIRECCION_GENERAL_DE_PROGRAMACION_Y_PREINVERSION = "DIRECCION GENERAL DE PROGRAMACION Y PREINVERSION";
    case UNIDAD_DE_PROGRAMACION_DE_LA_INVERSION = "UNIDAD DE PROGRAMACION DE LA INVERSION";
    case DIRECCION_GENERAL_DE_GESTION_DE_FINANCIAMIENTO_EXTERNO = "DIRECCION GENERAL DE GESTION DE FINANCIAMIENTO EXTERNO";
    case ORGANIZACION_NO_GUBERAMENTAL = "ORGANIACION NO GUBERNAMENTAL";
    case UNIDAD_DE_NEGOCIACION_DEL_FINANCIAMIENTO = "UNIDAD DE NEGOCIACION DEL FINANCIAMIENTO";
    case UNIDAD_OPERATIVA_DE_FINANCIAMIENTO = "UNIDAD OPERATIVA DE FINANCIAMIENTO";
    case UNIDAD_DE_ADMINISTRACION_DE_PROGRAMAS = "UNIDAD DE ADMINISTRACION DE PROGRAMAS";
    case DIRECCION_GENERAL_DE_GESTION_DE_LA_INVERSION_PUBLICA = "DIRECCION GENERAL DE GESTION DE LA INVERSION PUBLICA";
    case UNIDAD_DE_GESTION_DE_LA_INVERSION_TERRITORIAL = "UNIDAD DE GESTION DE LA INVERSION TERRITORIAL";
    case UNIDAD_DE_GESTION_DE_LA_INVERSION_SECTORIAL = "UNIDAD DE GESTION DE LA INVERSION SECTORIAL";
    case VICEMINISTERIO_DE_CIENCIA_Y_TECNOLOGÍA = "VICEMINISTERIO DE CIENCIA Y TECNOLOGÍA";
    case DIRECCIÓN_GENERAL_DE_CIENCIA_Y_CONOCIMIENTO = "DIRECCIÓN GENERAL DE CIENCIA Y CONOCIMIENTO";
    case DIRECCIÓN_GENERAL_DE_TECNOLOGÍA_E_INNOVACIÓN = "DIRECCIÓN GENERAL DE TECNOLOGÍA E INNOVACIÓN";
    case PROGRAMA_DE_INTERVENCIONES_URBANAS = "PROGRAMA DE INTERVENCIONES URBANAS";
    case UNIDAD_DE_COORDINACIÓN_GENERAL_DE_PLAN_NACIONAL_DE_EMPLEO = "UNIDAD DE COORDINACIÓN GENERAL DE PLAN NACIONAL DE EMPLEO";
}
